import { StyleSheet } from "react-native";

export const EditProgramStyles = StyleSheet.create({
  container: {
    minHeight: "100%",
    backgroundColor: "#0a0a0a",
    color: "#f6f6f6",
    paddingBottom: 24,
  },
  header: {
    backgroundColor: "#3a3a3a",
    paddingHorizontal: 16,
    paddingVertical: 20,
    alignItems: "center",
  },
  title: {
    fontFamily: "BebasNeue",
    fontSize: 36,
    color: "#f6f6f6",
    letterSpacing: 1.2,
  },
  programName: {
    width: "100%",
    padding: 16,
    backgroundColor: "#2a2a2a",
    color: "#f6f6f6",
    // borderRadius: 8,
    borderColor: "#5a5353",
    borderWidth: 2,
  },
  sectionsContainer: {
    paddingHorizontal: 16,
    paddingVertical: 24,
    flex: 1,
    gap: 16,
  },
  section: {
    backgroundColor: "#2a2a2a",
    // borderRadius: 8,
    padding: 16,
    borderWidth: 2,
    borderColor: "#5a5353",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: "#5a5353",
  },
  sectionInputContainer: {
    flex: 1,
    gap: 12,
  },
  sectionInput: {
    width: "100%",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#1a1a1a",
    borderWidth: 1,
    // borderRadius: 8,
    borderColor: "#5a5353",
    color: "#f6f6f6",
    fontWeight: "600",
  },
  trashBtn: {
    padding: 4,
    backgroundColor: "#5a5353",
    // borderRadius: 4,
    marginTop: 2,
    alignSelf: "flex-start",
  },
  exerciseContainer: {
    backgroundColor: "#1a1a1a",
    // borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: "#5a5353",
    marginVertical: 4,
    gap: 6,
  },
  exerciseHeader: {
    flexDirection: "row",
    gap: 6,
    alignContent: "center",
    alignItems: "baseline",
    justifyContent: "center",
  },
  exerciseInput: {
    width: "100%",
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#0a0a0a",
    borderWidth: 1,
    // borderRadius: 6,
    borderColor: "#5a5353",
    fontWeight: "600",
    color: "#f6f6f6",
    marginVertical: 4,
  },
  exerciseRow: {
    flexDirection: "row",
    gap: 8,
  },
  exerciseInputContainer: {
    flex: 1,
  },
  exerciseLabel: {
    fontWeight: "600",
    fontSize: 10,
    color: "#929292",
    marginTop: 4,
    marginBottom: -1,
  },
  addBtn: {
    flexDirection: "row",
    width: "100%",
    gap: 2,
    paddingVertical: 12,
    backgroundColor: "#3a3a3a",
    // borderRadius: 6,
    borderStyle: "dashed",
    borderColor: "#5a5353",
    borderWidth: 2,
    color: "#f6f6f6",
    fontWeight: "600",
    textAlign: "center",
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
  },
  addBtnText: {
    color: "#f6f6f6",
    fontWeight: "600",
    textAlign: "center",
  },
  divider: {
    height: 1,
    backgroundColor: "#5a5353",
    marginVertical: 12,
  },
  exerciseFooter: {
    fontSize: 10,
    color: "#929292",
    textAlign: "left",
    fontStyle: "italic",
  },
  footer: {
    height: 56,
    flexDirection: "row",
    // flex: 1,
    gap: 12,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 48,
    backgroundColor: "#0a0a0a",
    borderTopColor: "#5a5353",
    borderTopWidth: 2,
    width: "100%",
  },
  footerBtn: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    // backgroundColor: "#3a3a3a",
    // borderRadius: 6,
    // borderColor: "#5a5353",
    borderWidth: 2,
    flex: 1,
    // width: "100%",
  },
  footerBtnText: {
    // color: "#f6f6f6",
    fontWeight: "600",
    textAlign: "center",
  },
  footerCancelBtn: {
    backgroundColor: "#5a5353",
    color: "#f6f6f6",
  },
  footerSaveBtn: {
    backgroundColor: "#f6a800",
    color: "#0a0a0a",
  },
});
