import { StyleSheet } from "react-native";

export const EditProgramStyles = StyleSheet.create({
  container: {
    minHeight: "100%",
    backgroundColor: "#0a0a0a",
    color: "#f6f6f6",
    paddingBottom: 24,
  },
  header: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#222222",
  },
  title: {
    fontFamily: "BebasNeue",
    fontSize: 16,
    color: "#888888",
    letterSpacing: 1.2,
    marginBottom: 4,
  },
  programName: {
    width: "100%",
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "#181818",
    color: "#ffffff",
    fontFamily: "BebasNeue",
    fontSize: 26,
    letterSpacing: 0.8,
    borderColor: "#2e2e2e",
    borderWidth: 1,
  },
  workoutBtn: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: "#f6a800",
    alignSelf: "flex-start",
    marginBottom: 12,
  },
  sectionsContainer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    flex: 1,
    gap: 20,
  },
  section: {
    backgroundColor: "#141414",
    padding: 16,
    borderWidth: 1,
    borderColor: "#242424",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#242424",
  },
  sectionInputContainer: {
    flex: 1,
    gap: 8,
  },
  sectionInput: {
    width: "100%",
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "#1c1c1e",
    borderWidth: 1,
    borderColor: "#2c2c2e",
    color: "#ffffff",
    fontWeight: "600",
    fontSize: 15,
  },
  trashBtn: {
    padding: 8,
    backgroundColor: "#222224",
    alignItems: "center",
    justifyContent: "center",
  },
  exerciseContainer: {
    gap: 14,
    marginBottom: 12,
  },
  exerciseBox: {
    backgroundColor: "#1a1a1c",
    padding: 14,
    borderWidth: 1,
    borderColor: "#28282b",
    gap: 10,
  },
  exerciseHeader: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  exerciseInput: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#0e0e10",
    borderWidth: 1,
    borderColor: "#2a2a2d",
    fontWeight: "600",
    color: "#ffffff",
    fontSize: 14,
  },
  exerciseRow: {
    flexDirection: "row",
    gap: 10,
  },
  exerciseInputContainer: {
    flex: 1,
  },
  exerciseLabel: {
    fontWeight: "600",
    fontSize: 11,
    color: "#8e8e93",
    marginBottom: 4,
    fontFamily: "subHeaderText",
  },
  addBtn: {
    flexDirection: "row",
    width: "100%",
    gap: 6,
    paddingVertical: 12,
    backgroundColor: "#1c1c1e",
    borderColor: "#333336",
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  addBtnText: {
    color: "#ffffff",
    fontWeight: "600",
    fontFamily: "subHeaderText",
    fontSize: 14,
  },
  divider: {
    height: 1,
    backgroundColor: "#262628",
    marginVertical: 4,
  },
  exerciseFooter: {
    fontSize: 12,
    color: "#7c7c80",
    textAlign: "left",
    fontStyle: "italic",
    marginTop: 4,
  },
  footer: {
    height: 60,
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 60,
    backgroundColor: "#121212",
    borderTopColor: "#222222",
    borderTopWidth: 1,
    width: "100%",
  },
  footerBtn: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderWidth: 1,
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  footerBtnText: {
    fontWeight: "600",
    fontSize: 16,
    textAlign: "center",
  },
  footerCancelBtn: {
    backgroundColor: "#242426",
    borderColor: "#333336",
  },
  footerSaveBtn: {
    backgroundColor: "#f6a800",
    borderColor: "#f6a800",
  },
});
