import { StyleSheet } from "react-native";

export const indexStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0a0a0a",
    alignSelf: "center",
    width: "100%",
    justifyContent: "space-evenly",
    paddingBottom: 24,
  },
  header: {
    paddingTop: 24,
    paddingBottom: 16,
    flexDirection: "row",
    flex: 1,
    alignContent: "center",
    justifyContent: "center",
  },
  title: {
    fontFamily: "BebasNeue",
    fontSize: 64,
    textAlign: "center",
    color: "#f5f5f5",
    letterSpacing: 1.2,
    maxWidth: 350,
    marginHorizontal: 8,
    marginBottom: 24,
  },
  subText: {
    fontFamily: "italicFont",
    fontSize: 12,
    textAlign: "center",
    color: "#929292",
    marginBottom: 16,
  },
  recentPrograms: {
    flex: 1,
  },
  emptyProg: {
    width: "85%",
    paddingVertical: 16,
    marginHorizontal: "auto",
    marginBottom: 20,
    height: 110,
  },
  progButton: {
    width: "85%",
    paddingVertical: 16,
    paddingHorizontal: 18,
    backgroundColor: "#f6a800",
    marginHorizontal: "auto",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#d89400",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  cardHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  progText: {
    fontFamily: "BebasNeue",
    fontSize: 26,
    color: "#0a0a0a",
    letterSpacing: 0.8,
  },
  startBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#0a0a0a",
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 4,
  },
  startBadgeText: {
    fontFamily: "BebasNeue",
    fontSize: 16,
    color: "#f6a800",
    letterSpacing: 0.8,
  },
  workoutPreviewText: {
    fontFamily: "italicFont",
    fontSize: 13,
    color: "#3a3a3a",
    marginTop: 2,
  },
  cardDivider: {
    height: 1,
    backgroundColor: "rgba(0, 0, 0, 0.15)",
    marginVertical: 10,
  },
  metaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    rowGap: 6,
    columnGap: 10,
  },
  metaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  metaText: {
    fontFamily: "subHeaderText",
    fontSize: 13,
    color: "#1a1a1a",
  },
  otherButtonsContainer: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "nowrap",
    justifyContent: "space-between",
    marginBottom: 8,
    width: "85%",
    marginHorizontal: "auto",
  },
  otherButton: {
    backgroundColor: "#262626",
    width: "48%",
    justifyContent: "center",
    maxHeight: 100,
    borderWidth: 1,
    borderColor: "#333333",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  otherButtonText: {
    fontSize: 16,
    color: "#f5f5f5",
    fontFamily: "BebasNeue",
  },
  otherButtonLayout: {
    alignItems: "center",
    gap: 4,
  },
});
