import { StyleSheet } from "react-native";

export const ProgramsStylesheet = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0a0a0a",
    alignSelf: "center",
    width: "100%",
    justifyContent: "space-between",
  },
  loadingText: {
    fontFamily: "subHeaderText",
    fontSize: 18,
    color: "#929292",
    textAlign: "center",
    marginTop: 32,
  },
  header: {
    paddingTop: 24,
    paddingBottom: 16,
    flexDirection: "row",
    alignContent: "center",
    justifyContent: "center",
  },
  title: {
    fontFamily: "BebasNeue",
    fontSize: 40,
    textAlign: "center",
    color: "#f5f5f5",
    letterSpacing: 1.2,
    maxWidth: 350,
    marginHorizontal: 8,
    marginBottom: 24,
  },
  addButton: {
    width: "85%",
    paddingVertical: 16,
    backgroundColor: "#f6a800",
    marginHorizontal: "auto",
    marginBottom: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  addLayout: {
    gap: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  progLayout: {
    gap: 2,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  rowLayout: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  colLayout: {
    flex: 1,
    gap: 4,
  },
  addText: {
    fontFamily: "BebasNeue",
    fontSize: 24,
    color: "#0a0a0a",
  },
  headerText: {
    fontFamily: "subHeaderText",
    fontSize: 24,
    color: "#929292",
    textAlign: "center",
    marginBottom: 20,
  },
  progText: {
    fontFamily: "BebasNeue",
    fontSize: 26,
    color: "#f5f5f5",
    letterSpacing: 0.8,
  },
  subText: {
    fontFamily: "italicFont",
    fontSize: 16,
    color: "#929292",
  },
  progButton: {
    width: "85%",
    paddingVertical: 18,
    paddingHorizontal: 20,
    backgroundColor: "#1e1e1e",
    marginHorizontal: "auto",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#333333",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  cardHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  workoutPreviewText: {
    fontFamily: "italicFont",
    fontSize: 13,
    color: "#8e8e93",
    marginTop: 2,
  },
  cardDivider: {
    height: 1,
    backgroundColor: "#2a2a2e",
    marginVertical: 12,
  },
  metaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    rowGap: 8,
    columnGap: 12,
  },
  metaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  metaText: {
    fontFamily: "subHeaderText",
    fontSize: 13,
    color: "#b0b0b0",
  },
  errorText: {
    fontFamily: "subHeaderText",
    fontSize: 18,
    color: "#f44336",
    textAlign: "center",
    marginTop: 32,
  }
});
